// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from data.proto</summary>
public static partial class DataReflection {

  #region Descriptor
  /// <summary>File descriptor for data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpkYXRhLnByb3RvIrcBCgREYXRhEg4KBlNlcnZlchgBIAEoCRISCgpMYW5B",
          "ZGRyZXNzGAIgASgJEhEKCWNvbW11bml0eRgDIAEoCRIdCgR0eXBlGAQgASgO",
          "Mg8uRGF0YS5FbnlwdFR5cGUSEAoIUGFzc3dvcmQYBSABKAkiRwoJRW55cHRU",
          "eXBlEggKBE5PTkUQABILCgdUV09GSVNIEAESBwoDQUVTEAISDAoIQ0hBQ0hB",
          "MjAQAxIMCghTUEVDS0NUUhAEYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Data), global::Data.Parser, new[]{ "Server", "LanAddress", "Community", "Type", "Password" }, null, new[]{ typeof(global::Data.Types.EnyptType) }, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Data : pb::IMessage<Data>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Data> _parser = new pb::MessageParser<Data>(() => new Data());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Data> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Data() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Data(Data other) : this() {
    server_ = other.server_;
    lanAddress_ = other.lanAddress_;
    community_ = other.community_;
    type_ = other.type_;
    password_ = other.password_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Data Clone() {
    return new Data(this);
  }

  /// <summary>Field number for the "Server" field.</summary>
  public const int ServerFieldNumber = 1;
  private string server_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Server {
    get { return server_; }
    set {
      server_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "LanAddress" field.</summary>
  public const int LanAddressFieldNumber = 2;
  private string lanAddress_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string LanAddress {
    get { return lanAddress_; }
    set {
      lanAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "community" field.</summary>
  public const int CommunityFieldNumber = 3;
  private string community_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Community {
    get { return community_; }
    set {
      community_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 4;
  private global::Data.Types.EnyptType type_ = global::Data.Types.EnyptType.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Data.Types.EnyptType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "Password" field.</summary>
  public const int PasswordFieldNumber = 5;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Data);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Data other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Server != other.Server) return false;
    if (LanAddress != other.LanAddress) return false;
    if (Community != other.Community) return false;
    if (Type != other.Type) return false;
    if (Password != other.Password) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Server.Length != 0) hash ^= Server.GetHashCode();
    if (LanAddress.Length != 0) hash ^= LanAddress.GetHashCode();
    if (Community.Length != 0) hash ^= Community.GetHashCode();
    if (Type != global::Data.Types.EnyptType.None) hash ^= Type.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Server.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Server);
    }
    if (LanAddress.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(LanAddress);
    }
    if (Community.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Community);
    }
    if (Type != global::Data.Types.EnyptType.None) {
      output.WriteRawTag(32);
      output.WriteEnum((int) Type);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Server.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Server);
    }
    if (LanAddress.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(LanAddress);
    }
    if (Community.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Community);
    }
    if (Type != global::Data.Types.EnyptType.None) {
      output.WriteRawTag(32);
      output.WriteEnum((int) Type);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Server.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Server);
    }
    if (LanAddress.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LanAddress);
    }
    if (Community.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Community);
    }
    if (Type != global::Data.Types.EnyptType.None) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Data other) {
    if (other == null) {
      return;
    }
    if (other.Server.Length != 0) {
      Server = other.Server;
    }
    if (other.LanAddress.Length != 0) {
      LanAddress = other.LanAddress;
    }
    if (other.Community.Length != 0) {
      Community = other.Community;
    }
    if (other.Type != global::Data.Types.EnyptType.None) {
      Type = other.Type;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Server = input.ReadString();
          break;
        }
        case 18: {
          LanAddress = input.ReadString();
          break;
        }
        case 26: {
          Community = input.ReadString();
          break;
        }
        case 32: {
          Type = (global::Data.Types.EnyptType) input.ReadEnum();
          break;
        }
        case 42: {
          Password = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Server = input.ReadString();
          break;
        }
        case 18: {
          LanAddress = input.ReadString();
          break;
        }
        case 26: {
          Community = input.ReadString();
          break;
        }
        case 32: {
          Type = (global::Data.Types.EnyptType) input.ReadEnum();
          break;
        }
        case 42: {
          Password = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Data message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum EnyptType {
      [pbr::OriginalName("NONE")] None = 0,
      [pbr::OriginalName("TWOFISH")] Twofish = 1,
      [pbr::OriginalName("AES")] Aes = 2,
      [pbr::OriginalName("CHACHA20")] Chacha20 = 3,
      [pbr::OriginalName("SPECKCTR")] Speckctr = 4,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
